services:
  - type: web
    name: arealearn-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        value: mongodb+srv://root:12345@cluster1.b4n7frn.mongodb.net/arealearn?retryWrites=true&w=majority&appName=Cluster1
    autoDeploy: true 